name: Deploy to AWS
description: Deploy the app to AWS App Runner service.

inputs:
  service-name:
    description: App Runner service name
    required: true

  image-path:
    description: Docker image path
    required: true

  gemini-api-key-secret-arn:
    description: Gemini API Key secret ARN in Secrets Manager
    required: true

  google-sheet-id:
    required: true

  google-service-account-email:
    required: true

  google-private-key-secret-arn:
    description: Google Private Key secret ARN in Secrets Manager for service account
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@v5.1.1
      with:
        aws-region: ${{ env.REGION }}
        role-to-assume: ${{ env.GH_RUNNER_ROLE_ARN }}
        role-session-name: github-runner

    - name: Deploy app
      shell: bash
      run: |
        # Deploy app
        # -----------------------------
        # CONFIGURATION
        # -----------------------------
        AWS_ACCOUNT_ID="$(aws sts get-caller-identity --query 'Account' --output text)"
        ECR_ACCESS_ROLE_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:role/AppRunnerECRAccessRole"
        INSTANCE_ROLE_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:role/${{ env.APP_RUNNER_INSTANCE_ROLE_NAME }}"
        PORT="8080"

        # -----------------------------
        # CHECK IF SERVICE EXISTS
        # -----------------------------
        echo "Checking if App Runner service '${{ inputs.service-name }}' exists..."

        SERVICE_ARN=$(aws apprunner list-services \
          --query "ServiceSummaryList[?ServiceName=='${{ inputs.service-name }}'].ServiceArn" \
          --output text)

        if [ "$SERVICE_ARN" == "None" ] || [ -z "$SERVICE_ARN" ]; then
          echo "❌ Service does NOT exist. Creating a new one..."

          # -----------------------------
          # CREATE SERVICE
          # -----------------------------
          aws apprunner create-service \
            --service-name "${{ inputs.service-name }}" \
            --source-configuration "{
              \"ImageRepository\": {
                \"ImageIdentifier\": \"${{ inputs.image-path }}\",
                \"ImageRepositoryType\": \"ECR\",
                \"ImageConfiguration\": {
                  \"Port\": \"8080\",
                  \"RuntimeEnvironmentVariables\": [
                      {
                        \"GOOGLE_SHEET_ID\": \"${{ inputs.google-sheet-id }}\",
                        \"GOOGLE_SERVICE_ACCOUNT_EMAIL\": \"${{ inputs.google-service-account-email }}\"
                      }
                  ],
                  \"RuntimeEnvironmentSecrets\": [
                      {
                        \"GEMINI_API_KEY\": \"${{ inputs.gemini-api-key-secret-arn }}\",
                        \"GOOGLE_PRIVATE_KEY\": \"${{ inputs.google-private-key-secret-arn }}\"
                      }
                  ]
                }
              },
              \"AuthenticationConfiguration\": {
                \"AccessRoleArn\": \"$ECR_ACCESS_ROLE_ARN\"
              }
            }" \
            --instance-configuration "{
              \"Cpu\": \"${{ env.CPU }}\",
              \"Memory\": \"${{ env.MEMORY }}\",
              \"InstanceRoleArn\": \"$INSTANCE_ROLE_ARN\"
            }"

          echo "✅ Service created successfully."

        else
          echo "✅ Service exists: ${{ inputs.service-name }}"
          echo "Updating it with new image: ${{ inputs.image-path }}"

          # -----------------------------
          # UPDATE SERVICE (change image identifier)
          # -----------------------------
          aws apprunner update-service \
            --service-arn "$SERVICE_ARN" \
            --source-configuration "{
              \"ImageRepository\": {
                \"ImageIdentifier\": \"${{ inputs.image-path }}\",
                \"ImageRepositoryType\": \"ECR\",
                \"ImageConfiguration\": {
                  \"Port\": \"8080\",
                  \"RuntimeEnvironmentVariables\": [
                      {
                        \"GOOGLE_SHEET_ID\": \"${{ inputs.google-sheet-id }}\",
                        \"GOOGLE_SERVICE_ACCOUNT_EMAIL\": \"${{ inputs.google-service-account-email }}\"
                      }
                  ],
                  \"RuntimeEnvironmentSecrets\": [
                      {
                        \"GEMINI_API_KEY\": \"${{ inputs.gemini-api-key-secret-arn }}\",
                        \"GOOGLE_PRIVATE_KEY\": \"${{ inputs.google-private-key-secret-arn }}\"
                      }
                  ]
                }
              },
              \"AuthenticationConfiguration\": {
                \"AccessRoleArn\": \"$ECR_ACCESS_ROLE_ARN\"
              }
            }" \
            --instance-configuration "{
              \"Cpu\": \"${{ env.CPU }}\",
              \"Memory\": \"${{ env.MEMORY }}\",
              \"InstanceRoleArn\": \"$INSTANCE_ROLE_ARN\"
            }"

          echo "🚀 Update triggered successfully."
        fi
