name: Build Docker Image
description: Builds a Docker image with dynamic tag (git tag or commit sha).

inputs:
  image-tag:
    description: Docker image tag
    required: true

  react-app-initial-admin-email:
    required: true

  react-app-google-client-id:
    required: true

outputs:
  image-path:
    description: Docker image path
    value: ${{ steps.set-output.outputs.image-path }}

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      shell: bash
      run: |
        docker build \
          --build-arg REACT_APP_INITIAL_ADMIN_EMAIL="${{ inputs. }}" \
		      --build-arg REACT_APP_GOOGLE_CLIENT_ID="$(REACT_APP_GOOGLE_CLIENT_ID)" \
          -t ${{ env.DOCKER_REPO }}:${{ inputs.image-tag }} .

    - name: Set output
      id: set-output
      shell: bash
      run: echo "image-path=${{ env.DOCKER_REPO }}:${{ inputs.image-tag }}" >> "$GITHUB_OUTPUT"
