name: Build Docker Image
description: Builds a Docker image with dynamic tag (git tag or commit sha).

outputs:
  image-tag:
    description: Full Docker image tag
    value: ${{ steps.set-output.outputs.image-tag }}

runs:
  using: composite
  steps:
    - name: Generate tag (Git tag or commit SHA)
      id: gen-sha
      shell: bash
      run: |
        if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
          TAG="${GITHUB_REF_NAME}"
        else
          TAG=$(git rev-parse --short HEAD)
        fi

        echo "TAG=$TAG" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      shell: bash
      run: docker build -t ${{ vars.DOCKER_REPO }}:${TAG} .

    - name: Set output
      id: set-output
      shell: bash
      run: echo "image-tag=${{ vars.DOCKER_REPO }}:${TAG}" >> "$GITHUB_OUTPUT"