name: Deploy to GCP
description: Deploy the app to Google Cloud Run service.

inputs:
  service-name:
    description: Cloud Run service name
    required: true

  image-path:
    description: Docker image path
    required: true

  gemini-api-key-secret-name:
    description: Gemini API Key secret name in Secrets Manager
    required: true

  google-sheet-id:
    required: true

  google-service-account-email:
    required: true

  google-private-key-secret-name:
    description: Google Private Key secret name in Secrets Manager for service account
    required: true

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.GH_RUNNER_SA_KEY }}

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Verify auth
      shell: bash
      run: gcloud auth list

    - name: Deploy app
      shell: bash
      run: |
        gcloud run deploy ${{ inputs.service-name }} \
          --image ${{ inputs.image-path }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --no-invoker-iam-check \
          --memory ${{ env.MEMORY }} \
          --update-secrets GEMINI_API_KEY=${{ inputs.gemini-api-key-secret-name }}:latest \
          --set-env-vars GOOGLE_SHEET_ID="${{ inputs.google-sheet-id }}" \
          --set-env-vars GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ inputs.google-service-account-email }} \
          --update-secrets GOOGLE_PRIVATE_KEY=${{ inputs.google-private-key-secret-name }}:latest
